[phases.setup]
nixPkgs = ["nodejs_20", "pnpm"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["BASE_PATH=/ pnpm --filter @workspace/vanny-konveksi run build"]

[start]
cmd = "BASE_PATH=/ pnpm --filter @workspace/vanny-konveksi run serve"
